# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsoftware():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsoftware(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1550, 878)
    self.driver.find_element(By.CSS_SELECTOR, ".mb-16:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3Atext-blue-500").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Anshul")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("guptaanshul.1410@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".border-transparent").click()
    self.driver.find_element(By.CSS_SELECTOR, ".px-8").click()
    self.driver.find_element(By.NAME, "trainNumber").click()
    self.driver.find_element(By.NAME, "trainNumber").send_keys("12981")
    self.driver.find_element(By.NAME, "pnr").click()
    self.driver.find_element(By.NAME, "pnr").send_keys("3432534321")
    self.driver.find_element(By.NAME, "seat").click()
    self.driver.find_element(By.NAME, "seat").send_keys("B4-12")
    self.driver.find_element(By.NAME, "stationCode").click()
    self.driver.find_element(By.NAME, "stationCode").send_keys("MAS")
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(3) .px-6").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1) .px-4").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1) .px-4").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1) .px-4").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1) .px-4")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(2) .px-4").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(2) .px-4").click()
    self.driver.find_element(By.LINK_TEXT, "5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .w-full").send_keys("12981")
    self.driver.find_element(By.CSS_SELECTOR, ".grid > div:nth-child(2) > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid > div:nth-child(2) > .w-full").send_keys("B")
    self.driver.find_element(By.CSS_SELECTOR, ".grid > div:nth-child(2) > .w-full").send_keys("B4")
    self.driver.find_element(By.CSS_SELECTOR, ".grid > div:nth-child(3) > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid > div:nth-child(3) > .w-full").send_keys("12")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .w-full").send_keys("MAS")
    self.driver.find_element(By.CSS_SELECTOR, ".space-y-6 > div:nth-child(2) > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".space-y-6 > div:nth-child(2) > .w-full").send_keys("12,B4,Ahmedabad")
    self.driver.find_element(By.CSS_SELECTOR, ".space-y-6 > div:nth-child(3) > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".space-y-6 > div:nth-child(3) > .w-full").send_keys("Message me when you reach")
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1) > .flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-3").click()
    self.driver.find_element(By.LINK_TEXT, "My Orders").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-600:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-md").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("piyushjain76296@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".border-transparent").click()
    self.driver.find_element(By.LINK_TEXT, "Admin Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-white").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex-col").click()
    self.driver.close()
  
