// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test1', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1550, height: 878 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("piyushjain76296@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.css(".border-transparent")).click()
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.name("trainNumber")).click()
    await driver.findElement(By.name("trainNumber")).sendKeys("12981")
    await driver.findElement(By.name("pnr")).click()
    await driver.findElement(By.name("pnr")).sendKeys("442456543214")
    await driver.findElement(By.name("seat")).click()
    await driver.findElement(By.name("seat")).sendKeys("B1")
    await driver.findElement(By.name("stationCode")).click()
    await driver.findElement(By.name("seat")).click()
    await driver.findElement(By.name("seat")).sendKeys("B1-23")
    await driver.findElement(By.name("stationCode")).click()
    await driver.findElement(By.name("stationCode")).sendKeys("NDLS")
    await driver.findElement(By.css(".rounded-lg")).click()
    await driver.findElement(By.css(".border:nth-child(2) .px-6")).click()
    await driver.findElement(By.css(".border:nth-child(1) .px-4")).click()
    {
      const element = await driver.findElement(By.css(".border:nth-child(1) .px-4"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".border:nth-child(2) > .flex > .px-4")).click()
    await driver.findElement(By.css(".border:nth-child(3) .px-4")).click()
    await driver.findElement(By.css(".border:nth-child(3) .px-4")).click()
    {
      const element = await driver.findElement(By.css(".border:nth-child(3) .px-4"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".lucide-shopping-cart > path")).click()
    await driver.findElement(By.css(".w-full")).click()
    await driver.findElement(By.css("div:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css("div:nth-child(1) > .w-full")).sendKeys("12981")
    await driver.findElement(By.css(".grid > div:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".grid > div:nth-child(2) > .w-full")).sendKeys("B1")
    await driver.findElement(By.css(".grid > div:nth-child(3) > .w-full")).click()
    await driver.findElement(By.css(".grid > div:nth-child(3) > .w-full")).sendKeys("23")
    await driver.findElement(By.css("div:nth-child(4) > .w-full")).click()
    await driver.findElement(By.css("div:nth-child(4) > .w-full")).sendKeys("NDLS")
    await driver.findElement(By.css(".space-y-6 > div:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".space-y-6 > div:nth-child(2) > .w-full")).sendKeys("23,Platform-5")
    await driver.findElement(By.css(".space-y-6 > div:nth-child(3) > .w-full")).click()
    await driver.findElement(By.css(".space-y-6 > div:nth-child(3) > .w-full")).sendKeys("Call When You Arrived")
    await driver.findElement(By.css(".border:nth-child(1) .font-medium")).click()
    await driver.findElement(By.css(".py-3")).click()
    await driver.findElement(By.css(".text-white")).click()
  })
})
